# Generated by Django 6.0.1 on 2026-05-02 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, help_text='Отображаемое имя; если пусто — используется username.', max_length=150, verbose_name='display nickname'),
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(verbose_name='Целевые калории')),
                ('protein_g', models.FloatField(verbose_name='Белки, г')),
                ('fat_g', models.FloatField(verbose_name='Жиры, г')),
                ('carbs_g', models.FloatField(verbose_name='Углеводы, г')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'цель по КБЖУ',
                'verbose_name_plural': 'цели по КБЖУ',
            },
        ),
        migrations.CreateModel(
            name='UserBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField(verbose_name='Вес, кг')),
                ('height_cm', models.PositiveSmallIntegerField(verbose_name='Рост, см')),
                ('age_years', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('sex', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=16, verbose_name='Пол')),
                ('activity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=16, verbose_name='Активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'параметры тела',
                'verbose_name_plural': 'параметры тела',
            },
        ),
        migrations.CreateModel(
            name='WeightHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата измерения')),
                ('weight_kg', models.FloatField(verbose_name='Вес, кг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'запись истории веса',
                'verbose_name_plural': 'история веса',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_weight_history_user_date')],
            },
        ),
    ]
