# Generated by Django 6.0.1 on 2026-05-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_email',
            field=models.EmailField(blank=True, default='', help_text='Новый адрес после запроса смены почты до подтверждения по ссылке из письма.', max_length=254, verbose_name='email pending verification'),
        ),
    ]
