limit_req_zone $binary_remote_addr zone=api_limit:10m rate=50r/s;
limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=50r/s;

server {
    listen 80;
    server_name localhost;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /admin/ {
        include /etc/nginx/admin-allow.conf;
        deny all;
        proxy_pass http://web:8000;
    }

    location /auth/ {
        limit_req zone=auth_limit burst=50 delay=20;
        proxy_pass http://web:8000;
    }

    location /api/ {
        limit_req zone=api_limit burst=100 delay=50;
        proxy_pass http://web:8000;
    }

    location / {
        proxy_pass http://web:8000;
    }
}