swagger: '2.0'
info:
  title: API for mobile
  description: АПИ для мобильного приложения подсчет каллорий и тренировок
  version: v1
host: 127.0.0.1:8000
schemes:
- http
basePath: /
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: 'Введите ваш JWT токен в формате: Bearer <ваш_токен>'
security:
- Bearer: []
paths:
  /api/meals/:
    get:
      operationId: api_meals_list
      description: Получить список всех приемов пищи пользователя
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Meal'
        '401':
          description: Пользователь не авторизован
      tags:
      - Приемы пищи
    post:
      operationId: api_meals_create
      description: Создать новый прием пищи
      parameters:
      - name: data
        in: body
        required: true
        schema:
          required:
          - product
          - name
          - amount
          type: object
          properties:
            product:
              description: ID продукта
              type: integer
              example: 1
            name:
              description: Название приема пищи
              type: string
              example: Завтрак
            amount:
              description: Количество в граммах
              type: integer
              example: 150
            position:
              description: Порядковый номер
              type: integer
              example: 1
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Meal'
        '400':
          description: Неверные данные
        '401':
          description: Пользователь не авторизован
      tags:
      - Приемы пищи
    parameters: []
  /api/meals/{id}/:
    get:
      operationId: api_meals_read
      description: Получить детальную информацию о приеме пищи
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Meal'
        '401':
          description: Пользователь не авторизован
        '404':
          description: Прием пищи не найден
      tags:
      - Приемы пищи
    put:
      operationId: api_meals_update
      description: Обновить прием пищи
      parameters:
      - name: data
        in: body
        required: true
        schema:
          required:
          - product
          - name
          - amount
          type: object
          properties:
            product:
              description: ID продукта
              type: integer
              example: 2
            name:
              description: Название приема пищи
              type: string
              example: Обед
            amount:
              description: Количество в граммах
              type: integer
              example: 200
            position:
              description: Порядковый номер
              type: integer
              example: 2
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Meal'
        '400':
          description: Неверные данные
        '401':
          description: Пользователь не авторизован
        '404':
          description: Прием пищи не найден
      tags:
      - Приемы пищи
    patch:
      operationId: api_meals_partial_update
      description: Частично обновить прием пищи
      parameters:
      - name: data
        in: body
        required: true
        schema:
          type: object
          properties:
            product:
              description: ID продукта (необязательно)
              type: integer
              example: 3
            name:
              description: Название приема пищи (необязательно)
              type: string
              example: Ужин
            amount:
              description: Количество в граммах (необязательно)
              type: integer
              example: 180
            position:
              description: Порядковый номер (необязательно)
              type: integer
              example: 3
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Meal'
        '400':
          description: Неверные данные
        '401':
          description: Пользователь не авторизован
        '404':
          description: Прием пищи не найден
      tags:
      - Приемы пищи
    delete:
      operationId: api_meals_delete
      description: Удалить прием пищи
      parameters: []
      responses:
        '204':
          description: Прием пищи удален
        '401':
          description: Пользователь не авторизован
        '404':
          description: Прием пищи не найден
      tags:
      - Приемы пищи
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this Прием пищи.
      required: true
      type: integer
  /api/products/:
    get:
      operationId: api_products_list
      description: Получить список всех продуктов
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        '401':
          description: Пользователь не авторизован
      tags:
      - Продукты
    parameters: []
  /api/products/{id}/:
    get:
      operationId: api_products_read
      description: Получить детальную информацию о продукте
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Product'
        '401':
          description: Пользователь не авторизован
        '404':
          description: Продукт не найден
      tags:
      - Продукты
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this Продукт.
      required: true
      type: integer
  /auth/jwt/create/:
    post:
      operationId: auth_jwt_create_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/TokenObtainPair'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/TokenObtainPair'
      tags:
      - auth
    parameters: []
  /auth/jwt/refresh/:
    post:
      operationId: auth_jwt_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/TokenRefresh'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/TokenRefresh'
      tags:
      - auth
    parameters: []
  /auth/jwt/verify/:
    post:
      operationId: auth_jwt_verify_create
      description: |-
        Takes a token and indicates if it is valid.  This view provides no
        information about a token's fitness for a particular use.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/TokenVerify'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/TokenVerify'
      tags:
      - auth
    parameters: []
  /auth/users/:
    get:
      operationId: auth_users_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
      tags:
      - auth
    post:
      operationId: auth_users_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/CustomUserCreate'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/CustomUserCreate'
      tags:
      - auth
    parameters: []
  /auth/users/activation/:
    post:
      operationId: auth_users_activation
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Activation'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Activation'
      tags:
      - auth
    parameters: []
  /auth/users/me/:
    get:
      operationId: auth_users_me_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
      tags:
      - auth
    put:
      operationId: auth_users_me_update
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/User'
      tags:
      - auth
    patch:
      operationId: auth_users_me_partial_update
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/User'
      tags:
      - auth
    delete:
      operationId: auth_users_me_delete
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - auth
    parameters: []
  /auth/users/resend_activation/:
    post:
      operationId: auth_users_resend_activation
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/SendEmailReset'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SendEmailReset'
      tags:
      - auth
    parameters: []
  /auth/users/reset_password/:
    post:
      operationId: auth_users_reset_password
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/SendEmailReset'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SendEmailReset'
      tags:
      - auth
    parameters: []
  /auth/users/reset_password_confirm/:
    post:
      operationId: auth_users_reset_password_confirm
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/PasswordResetConfirm'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/PasswordResetConfirm'
      tags:
      - auth
    parameters: []
  /auth/users/reset_username/:
    post:
      operationId: auth_users_reset_username
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/SendEmailReset'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SendEmailReset'
      tags:
      - auth
    parameters: []
  /auth/users/reset_username_confirm/:
    post:
      operationId: auth_users_reset_username_confirm
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/UsernameResetConfirm'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/UsernameResetConfirm'
      tags:
      - auth
    parameters: []
  /auth/users/set_password/:
    post:
      operationId: auth_users_set_password
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/SetPassword'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SetPassword'
      tags:
      - auth
    parameters: []
  /auth/users/set_username/:
    post:
      operationId: auth_users_set_username
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/SetUsername'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SetUsername'
      tags:
      - auth
    parameters: []
  /auth/users/{id}/:
    get:
      operationId: auth_users_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/User'
      tags:
      - auth
    put:
      operationId: auth_users_update
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/User'
      tags:
      - auth
    patch:
      operationId: auth_users_partial_update
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/User'
      tags:
      - auth
    delete:
      operationId: auth_users_delete
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - auth
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this пользователь.
      required: true
      type: integer
definitions:
  Meal:
    required:
    - product
    - name
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      product:
        title: Продукт
        type: integer
      name:
        title: Название приема пищи
        type: string
        maxLength: 255
        minLength: 1
      amount:
        title: Количество порций
        type: integer
        maximum: 9223372036854775807
        minimum: -9223372036854775808
      position:
        title: Порядковый номер
        type: integer
        maximum: 9223372036854775807
        minimum: -9223372036854775808
      date:
        title: Дата приема пищи
        type: string
        format: date-time
        readOnly: true
      calories:
        title: Калории (ккал)
        type: integer
        readOnly: true
        x-nullable: true
      protein:
        title: Белки (г)
        type: number
        readOnly: true
      carbohydrates:
        title: Углеводы (г)
        type: number
        readOnly: true
      fats:
        title: Жиры (г)
        type: number
        readOnly: true
  Product:
    required:
    - name
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      name:
        title: Название
        type: string
        maxLength: 255
        minLength: 1
      extra_info:
        title: Дополнительная информация
        type: string
      net_weight:
        title: Вес нетто (г)
        type: number
      number_of_servings:
        title: Количество порций
        type: integer
        maximum: 9223372036854775807
        minimum: -9223372036854775808
      producer:
        title: Производитель
        type: string
        maxLength: 255
      product_category:
        title: Категория продукта
        type: string
        maxLength: 100
      calories:
        title: Калории (ккал)
        type: integer
        maximum: 9223372036854775807
        minimum: -9223372036854775808
        x-nullable: true
      protein:
        title: Белки (г)
        type: number
      carbohydrates:
        title: Углеводы (г)
        type: number
      fats:
        title: Жиры (г)
        type: number
  TokenObtainPair:
    required:
    - username
    - password
    type: object
    properties:
      username:
        title: Username
        type: string
        minLength: 1
      password:
        title: Password
        type: string
        minLength: 1
  TokenRefresh:
    required:
    - refresh
    type: object
    properties:
      refresh:
        title: Refresh
        type: string
        minLength: 1
      access:
        title: Access
        type: string
        readOnly: true
        minLength: 1
  TokenVerify:
    required:
    - token
    type: object
    properties:
      token:
        title: Token
        type: string
        minLength: 1
  User:
    type: object
    properties:
      email:
        title: Адрес электронной почты
        type: string
        format: email
        readOnly: true
        minLength: 1
      id:
        title: ID
        type: integer
        readOnly: true
  CustomUserCreate:
    required:
    - email
    - password
    type: object
    properties:
      email:
        title: Адрес электронной почты
        type: string
        format: email
        maxLength: 254
        minLength: 1
      password:
        title: Password
        type: string
        minLength: 1
  Activation:
    required:
    - uid
    - token
    type: object
    properties:
      uid:
        title: Uid
        type: string
        minLength: 1
      token:
        title: Token
        type: string
        minLength: 1
  SendEmailReset:
    required:
    - email
    type: object
    properties:
      email:
        title: Email
        type: string
        format: email
        minLength: 1
  PasswordResetConfirm:
    required:
    - uid
    - token
    - new_password
    type: object
    properties:
      uid:
        title: Uid
        type: string
        minLength: 1
      token:
        title: Token
        type: string
        minLength: 1
      new_password:
        title: New password
        type: string
        minLength: 1
  UsernameResetConfirm:
    required:
    - new_email
    type: object
    properties:
      new_email:
        title: Адрес электронной почты
        type: string
        format: email
        maxLength: 254
        minLength: 1
  SetPassword:
    required:
    - new_password
    - current_password
    type: object
    properties:
      new_password:
        title: New password
        type: string
        minLength: 1
      current_password:
        title: Current password
        type: string
        minLength: 1
  SetUsername:
    required:
    - current_password
    - new_email
    type: object
    properties:
      current_password:
        title: Current password
        type: string
        minLength: 1
      new_email:
        title: Адрес электронной почты
        type: string
        format: email
        maxLength: 254
        minLength: 1
