# Generated by Django 6.0.1 on 2026-01-07 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('extra_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('net_weight', models.FloatField(blank=True, default=0.0, verbose_name='Вес нетто (г)')),
                ('number_of_servings', models.IntegerField(blank=True, default=1, verbose_name='Количество порций')),
                ('producer', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('product_category', models.CharField(blank=True, max_length=100, verbose_name='Категория продукта')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Калории (ккал)')),
                ('protein', models.FloatField(default=0.0, verbose_name='Белки (г)')),
                ('carbohydrates', models.FloatField(default=0.0, verbose_name='Углеводы (г)')),
                ('fats', models.FloatField(default=0.0, verbose_name='Жиры (г)')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название приема пищи')),
                ('amount', models.IntegerField(default=100, verbose_name='Количество порций')),
                ('position', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата приема пищи')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Калории (ккал)')),
                ('protein', models.FloatField(default=0.0, verbose_name='Белки (г)')),
                ('carbohydrates', models.FloatField(default=0.0, verbose_name='Углеводы (г)')),
                ('fats', models.FloatField(default=0.0, verbose_name='Жиры (г)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Прием пищи',
                'verbose_name_plural': 'Приемы пищи',
                'ordering': ['-date', 'position'],
            },
        ),
    ]
