# Generated by Django 6.0.1 on 2026-04-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_trigram_search_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='unit',
            field=models.CharField(blank=True, default='граммы', max_length=255, verbose_name='Единица измерения'),
        ),
    ]
