# Generated by Django 6.0.1 on 2026-04-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_meal_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='unit',
            field=models.CharField(blank=True, default='gramms', max_length=255, verbose_name='Единица измерения'),
        ),
    ]
