# Generated by Django 6.0.1 on 2026-04-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_meal_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='name',
            new_name='type',
        ),
    ]
