# Generated by Django 6.0.1 on 2026-05-05 06:17

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('plan', 'Plan'), ('set', 'Set')], max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('nodes', models.JSONField(default=list)),
                ('muscle_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text='Группы мышц из упражнений узлов (для фильтра /api/sets)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anchor_date', models.DateField()),
                ('interval_days', models.PositiveIntegerField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_assignments', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='training.workouttemplate')),
            ],
            options={
                'ordering': ['sort_order', 'anchor_date'],
            },
        ),
        migrations.CreateModel(
            name='DayCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_day_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_training_daycompletion_user_date')],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_muscles', models.JSONField(default=list)),
                ('muscle_group', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Legs', 'Legs'), ('Core', 'Core'), ('Glutes', 'Glutes'), ('Calves', 'Calves'), ('FullBody', 'Full Body')], max_length=32)),
                ('approaches', models.JSONField(default=list)),
                ('user', models.ForeignKey(blank=True, help_text='null — глобальное упражнение', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'name'], name='training_ex_user_id_95d2e1_idx'), models.Index(fields=['muscle_group'], name='training_ex_muscle__d092b3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workouttemplate',
            index=models.Index(fields=['user', 'kind'], name='training_wo_user_id_f64bca_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttemplate',
            index=models.Index(fields=['user', 'kind', 'name'], name='training_wo_user_id_af11b2_idx'),
        ),
        migrations.AddIndex(
            model_name='templateassignment',
            index=models.Index(fields=['user'], name='training_te_user_id_9afbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='templateassignment',
            index=models.Index(fields=['user', 'sort_order'], name='training_te_user_id_cae359_idx'),
        ),
    ]
