# Generated by Django 6.0.1 on 2026-05-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_assignmenttemplate_workoutset_approach_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='is_done',
            field=models.BooleanField(db_index=True, default=False, help_text='Отмечен ли подход выполненным (на уровне шаблона — общий для всех назначений по этому шаблону).'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_done',
            field=models.BooleanField(db_index=True, default=False, help_text='Тренировка по этому назначению выполнена.'),
        ),
    ]
